### ISSUE TITLE
move control reads into scraps

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/PacBioFileFormats#27]
Instead of having multiple `control.bam` files, Armin and I want to move control reads into scraps.

The challenge here is that we only have a single scrap type designator which we use for two concepts: scrap types and region types.  Control filtering happens post region-segmentation, so for a control ZMW we will have multiple region types---we can't encode both the region type and "CONTROL" in the one field we have available!

It seems like we probably need two designators: region type and scrap type. But it's worth noting that we already are doing something like "region type" via the READTYPE in the readgroup,  I don't think we want "region type" in two separate places.

So this requires some thinking and possible redesign.

**Comment by dalexander** [comment]
@armintoepfer

**Comment by armintoepfer** [comment]
My thoughts are, keep the READTYPE that discriminates between normal and scraps. Scraps is everything that is not meant to be used for downstream analysis.
Everything in the scraps.bam has to be classified and annotated:

1. Classification occurs on a per ZMW level, distinguish between spike-in controls, sentinels of the basecaller, and real customer molecules. I'd propose to call it scrap classification tag **sc**
2. A region-wise annotation to label adapters, barcodes, low-quality regions, and filtered. This used to be the **sc** tag. I'd suggest to call it scrap label tag **sl**

**Comment by dalexander** [comment]
This is a reasonable approach, and it would enable the removal of the control.bam files, which is a big win.  Maybe we should use **sr** ("scrap regiontype") instead of **sl**?

**Comment by armintoepfer** [comment]
Resolved with 3.0.3
