### ISSUE TITLE
`bq` tag spec is ambiguous 

### ISSUE THREAD

**Issue by armintoepfer** [PacificBiosciences/PacBioFileFormats#38]
There are three different definitions of the `bq` tag, we need to clarify and unify. Details here: https://github.com/PacificBiosciences/PacBioFileFormats/commit/cc5c8efd7eca7b4bccb966e99aff4aaa611c92b1#commitcomment-17936775

**Comment by armintoepfer** [comment]
To me it looks like we'll stick with the current barcode score model for a bit longer, thus we should increase the integer size to int16.

**Comment by dalexander** [comment]
Can we get @bnbowman's feedback in here?  Does a byte provide inadequate precision?  Just be conscious of the size impact (esp. on the pbi)

**Comment by dalexander** [comment]
As to the signed/unsigned, I think we should keep it unsigned, with the convention that uint8_max (255) refers to "missing" or "NA"

**Comment by jrharting** [comment]
how would using the convention that 255 is missing/NA affect filtering in the dataset xml model?

**Comment by dalexander** [comment]
Presumably reads with missing/NA barcode or barcode score would not pass any filter.  I don't think the particular encoding changes that.

**Comment by jrharting** [comment]
as long as its transparent to users, how its encoded does not concern me from an apps perspective.   Empirically, I would not expect to question calls/precision for barcodes with bq>127 unless the barcdes were really long, probably >50bp.  But it is something I would have to explain to the odd customer like Roche as long as we are recording SW alignments scores in that tag.  I can do that temporarily if it makes it easier for long-term specs from the dev end.

**Comment by armintoepfer** [comment]
I've talked to jrharting and I'd like to propose a normalized bq score. 

First of all, the current scores cannot be interpreted or used for filtering, as I can change alignment scores any time and destroy any of your golden assumptions. Secondly, with growing length, we need bigger ints to store those scores.

How about, we normalize the SW alignment score by barcodeLength * matchScore? We'd round that int and get a number between 0 - 100.
This way, we can keep the 1 Byte and get meaning into the score until we have a probabilistic model.

**Comment by bnbowman** [comment]
"""How about, we normalize the SW alignment score by barcodeLength * matchScore? We'd round that int and get a number between 0 - 100"""

That sounds reasonable to me

**Comment by jrharting** [comment]
ditto brett's comment

**Comment by armintoepfer** [comment]
@dalexander can we move forward on this and put this in for Fox?

**Comment by dalexander** [comment]
Yes, I will approve for Fox if you and Brett outline the work that will be required to get this implemented, and what applications will be impacted.

**Comment by dalexander** [comment]
...and we need someone to submit a spec revision as a PR

**Comment by armintoepfer** [comment]
I will do that today
