### ISSUE TITLE
bax2bam fails on public saccharomyces RSII P4-C2 data

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/PacBioFileFormats#47]
Trying to convert RSII yeast data it to BAM to proceed with other apps. My executables are those coming with the current version 4 of SMRT (4.0.0.190159+190159-190159-189856-189856-189856).
The data comes from [Saccharomyces-cerevisiae-W303-Assembly-Contigs](https://github.com/PacificBiosciences/DevNet/wiki/Saccharomyces-cerevisiae-W303-Assembly-Contigs)

**I get this error with all data trio-files:**
```
bax2bam h5_data/m130607_131654_42207_c100539492550000001823089611241313_s1_p0.1.bax.h5 \
h5_data/m130607_131654_42207_c100539492550000001823089611241313_s1_p0.2.bax.h5 \
h5_data/m130607_131654_42207_c100539492550000001823089611241313_s1_p0.3.bax.h5
ERROR: BindingKit, SequencingKit, and ChangeListID are mandatory but unavailable
```
Thanks for help!

**Comment by bhagya-ct** [comment]
Ran into same error.

The data comes from https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP028627

Hope someone helps.

**Comment by splaisan** [comment]
It has to do with some metadata from RSII which is not supported by the current software.
The fields reported in the error above are only added by recent pipelines and required for the conversion app to accept to run.
I had to quit on this data if I remember well :-(
You may try to add manually these fields and their values to the data you got from SRA to make it compatible or obtain an old version of the conversion software from an old RSII build.
Another possibility is to extract the sequence from the BAM and make a fasta out of it using some shell magic.
Hope this helps
S

**Comment by bhagya-ct** [comment]
Thank you for the reply. 

I will try to add manually. 

Thank you once again.

**Comment by RenhaoL** [comment]
Hi there, 

I am running into the same issue. I was wondering if you successfully added the parameters manually? If yes, do you mind share how you did it? 

Thanks in advance!

**Comment by splaisan** [comment]
no change, sorry!
