### ISSUE TITLE
qs/qe qStart/qEnd QueryStart/QueryEnd semantics for CCS

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/PacBioFileFormats#5]
What is/should the bam.pbi look like for CCS input?  Current we populate qStart and qEnd with default values, corresponding to the absence of the qs, qe tags; this is good but Nat has pointed out that this means there's no way to see the read lengths from the bam.pbi file.

**Comment by dalexander** [comment]
@nlhepler

**Comment by dalexander** [comment]
Part of me wonders whether we should have defined qStart, qEnd differently for CCS bam records---just letting them be (0, ccsReadLength) as people seem to expect.

**Comment by nlhepler** [comment]
Hmm....

**Comment by dalexander** [comment]
# The current state
`qs`, `qe` tags are defined to refer to position within the polymerase read, and thus are not meaningful for CCS reads.  So we don't emit them in CCS, and we leave the corresponding bam.pbi columns blank

# The dilemma
This makes the BAM pbi file almost useless for CCS, because you can't even access readlength.  Since we are trying to use bam.pbi as an expedient for reports (instead of having reports code iterate the BAM file), this is somewhat problematic.

# Possible paths forward
1) Do nothing, keep things as is, and indicate in the bam.pbi spec that this is the way it is
2) Update bam and bam.pbi specs to indicate that in the context of CCS, qs/qe/qStart/qEnd do not refer to the polymerase read, they are just (0, ccsReadLength).  In this world. qs/qe refer more generically to the coordinates of the query in the upstream file.
3)  Keep bam spec intact but change qs, qe columns to reflect (0, ccsReadLength). 

I think (1) and (2) are fine, (3) seems a bit gross.

**Comment by evolvedmicrobe** [comment]
My vote is definitely for (1), as I think it is a bit confusing to have the same field mean different things in a different context.  I also don't think adding them to the .pbi file helps much.  A typical subreads BAM file is >= 1.5G, while after being condensed to a CCS bam file its ~ 20 MB.  This means you can parse a CCS BAM file in under two seconds, and you get all the additional information that is not available in the pbi file to generate reports with while doing this.  Given the small data size, I just don't see a big advantage to the pbi file in this case.

**Comment by dalexander** [comment]
I can live with (1), but I want us to consider (2) or (3) a bit longer.

I agree with you that qs/qe are inherently pretty meaningless for ccs data.

Perhaps (3) or something like (3) isn't so bad?  Another option would be to add an explicit `readLength` column---redundant, to be sure, though perhaps we could remove the qEnd column to mitigate this.  There has also been the suggestion of adding 'np' to the bam.pbi.

The pbi is a bigger deal than you might realize.  It's an opportunity to normalize the important summary statistics *once* in a data frame, rather than having many tools scan the BAM file repeatedly.  

Also, you're not thinking big enough scale-wise.  Imagine a job of 20 movies like this.  Everything seemed "small" when we started, but data volume and job size just keep going up.

**Comment by natechols** [comment]
The files are small but iterating over many records in Python is still pretty slow, and it happens in many places.  I think there are some inefficiencies in our code that could be improved (I may have just figured out how to fix some of them), but even 20MB of CCS reads can take a while to get through.  My vote would be for adding readLength and np; I'm agnostic on the qs/qe semantics issue.

**Comment by evolvedmicrobe** [comment]
I of course defer to consumers of the pbi file to decide what they prefer.  For ccs data I usually generate the summary dataframes with ccscheck, which is insanely inefficient in terms of unnecessary copy and conversion operations, but which can process a 12 MB file in ~ 4 seconds so I haven't even bothered looking at speeding it up.  For R&D purposes we need more information than the pbi file provides, but whatever helps the standard reporting pipeline with pbi is obviously fine by me.

**Comment by dalexander** [comment]
I am warming up to the idea of keeping the semantics all the same, but dropping `qEnd` from the pbi and replacing it with `readLength`; and adding a `numPasses` column for good measure.  This would be for BAM 3.0.8 spec version, so not particularly soon.  Or am I getting too fancy?  I definitely feel the BAM spec fatigue.

**Comment by dalexander** [comment]
---the pbcore bam.pbi API already provides some "implied" columns (not stored in the file), so I would just add qEnd to that list.  R could do the same.

**Comment by natechols** [comment]
I think these additions would be useful - however I am not particularly
eager to update all of our testing .bam files again, so if this change can
be done without breaking 3.0b7 files, it would be much easier to endorse.

**Comment by dalexander** [comment]
One more thing to add to the discussion here.  Nat suggested having pbbam QueryStart/QueryEnd return (0, ccsReadLength).  

It's worth bringing Derek into the discussion.  He built a pretty comprehensive "clipping" API that assumes some kind of underlying coordinate system.  We should understand the implications there.

**Comment by armintoepfer** [comment]
I had a problem with clipping if qs and qe were not available (used bwa to align). Derek said that he falls back to the read name indices and if they are not available, 0 and readlength. Not sure if this is already implemented.

**Comment by dalexander** [comment]
@pezmaster31

**Comment by pezmaster31** [comment]
> I am warming up to the idea of keeping the semantics all the same, but dropping qEnd from the pbi and replacing it with readLength; and adding a numPasses column for good measure. This would be for BAM 3.0.8 spec version, so not particularly soon.

This makes sense to me.

> I think these additions would be useful - however I am not particularly
eager to update all of our testing .bam files again, so if this change can
be done without breaking 3.0b7 files, it would be much easier to endorse.

PBI has a built-in format version number, so we can support the 3.07b files at least for now, by switching behavior based on that value. Not sure how much a headache that will be at query time & using the data, but as far as slurping data that's easy enough. 

> One more thing to add to the discussion here. Nat suggested having pbbam QueryStart/QueryEnd return (0, ccsReadLength).
> I had a problem with clipping if qs and qe were not available (used bwa to align). Derek said that he falls back to the read name indices and if they are not available, 0 and readlength. Not sure if this is already implemented.

For BamRecord::Query<Start|End>, if the qe/qs tag is present, then that value is simply returned. If th are missing, then for CCS reads, an exception is thrown, per conversations with @nlhepler. For all other reads, the record name is parsed to extract the proper value. If it cannot be found, the final fallback is (0, 0). 

This behavior can certainly be modified if needed, but that's where it stands currently. That zero fallback for query end is probably incorrect, either way.
