### ISSUE TITLE
gcpp and ccs bam file

### ISSUE THREAD

**Issue by mekkiboussaha** [PacificBiosciences/PacBioFileFormats#53]
Dear all, 
I am really new in the field of PacBio sequence analysis and I first apologize if my question is stupid.
I have created a ccs bam file using the ccs package and then aligned the ccs data on my reference genome. I wanted to use gcpp for variant calling, I got this message error. I don't know how to interpret/correct this error. Can anyone help me please?
Thank you very much
Regards
Mekki
**Error :**
>|> 20200326 14:13:51.291 -|- FATAL -|- operator() -|- 0x7fe28bcdc780|| -|- caught exception: "m64122_200304_180044/129237834/ccs is missing the 'pw' tag, which is required for Arrow"
>|> 20200326 14:13:51.291 -|- FATAL -|- operator() -|- 0x7fe28bcdc780|| -|- caught SIGABRT
/var/spool/slurm/d/job12064503/slurm_script: line 35: 189539 Aborted                 gcpp -r $ref -x 3 -o $snp_gcpp $bam
>|> 20200326 14:14:31.375 -|- WARN -|- ParseInputFiles -|- 0x7fe10c135740|| -|- Detected CCS input, will not output SAC info! Overriding --call-min-reads-per-strand-all-samples to 0!

**Comment by armintoepfer** [comment]
You can't use gcpp to polish CCS output. For variant calling, you should look up deepvariant from Google.

**Comment by mekkiboussaha** [comment]
?ok thank you very much

regards


________________________________
De : Armin Töpfer <notifications@github.com>
Envoyé : jeudi 26 mars 2020 15:50
À : PacificBiosciences/PacBioFileFormats
Cc : Mekki Boussaha; Author
Objet : Re: [PacificBiosciences/PacBioFileFormats] gcpp and ccs bam file (#53)


You can't use gcpp to polish CCS output. For variant calling, you should look up deepvariant from Google.

-
