### ISSUE TITLE
Error while running gcpp

### ISSUE THREAD

**Issue by devenderarora** [PacificBiosciences/PacBioFileFormats#54]
Dear PacBio Community
I am facing an issue with polishing of Canu fasta output file. 
I am running the gcpp bamfile.bam -r canu.fasta --algorithm=arrow --output polish.fasta
While doing so I am getting an error
>|> 20200730 23:44:05.738 -|- FATAL -|- operator() -|- 0x7f3760dfe780|| -|- caught exception: "[pbbam] FASTA sequence cache ERROR: could not retrieve sequence loength, reference 'tig00000007' not found"

May I know how can I fix this error.
I will be grateful to you.

**Comment by armintoepfer** [comment]
Did you ensure that the fasta file actually contains all reference sequences of your alignment?

**Comment by devenderarora** [comment]
Dear Armin Töpfer,
Thanks for prompt response. I did explore both bam and fasta files and just did sorting to bam file and ran again. It is currently running. 
Thankyou.
